# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5abb80631ae26cef1dcc1956f9a8c7bed0a9fa3f9e144fe68f97d468289ce62a73018bed6baa0a6d9088644e031d00e0b0e0e7b581c4638706f825d070d95e62

test:
  secret_key_base: cfeef4c54dab2906b0a60085cfc2286a52f98fe0a9878858b7fec9e0cca52d89e4c997e3f30b536be08ed7d9133c36ebf6e355640fb9098de18ff72787cc1ba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
